### ISSUE TITLE
Fails to initialize

### ISSUE THREAD

**Issue by cdhassell** [CiviCooP/be.werkmetzin.wpcivi#1]
Thank you for this plugin!  

I have not been able to get it to install properly.  It produces this error:
`Sorry but we are not able to provide this at the moment.
Could not load option_groups configuration file for extension, contact your system administrator!`
This is on WP 4.4.2, Civicrm 4.7.3, PHP 5.6.18.
The backtrace is lengthy, see the attached zip file.
[civicrmerror.log.zip](https://github.com/CiviCooP/be.werkmetzin.wpcivi/files/170409/civicrmerror.log.zip)

**Comment by jaapjansma** [comment]
Not sure what happens exactly but as the readme states this is a customer specific extension which contains a framework which potentially could be reused. 

Also keep in mind that we are not software vendor so we do not provide the provide the product. We share our code with the public so others could use it and change it.

**Comment by ErikHommel** [comment]
This means that the extension could not access the JSON file option_groups in the resources folder. It probably means that you have to change the permissions for that folder.

Verstuurd vanaf mijn iPad

Op 12 mrt. 2016 om 14:05 heeft cdhassell <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Thank you for this plugin!

I have not been able to get it to install properly. It produces this error:
Sorry but we are not able to provide this at the moment.
Could not load option_groups configuration file for extension, contact your system administrator!
This is on WP 4.4.2, Civicrm 4.7.3, PHP 5.6.18.
The backtrace is lengthy, see the attached zip file.
civicrmerror.log.ziphttps://github.com/CiviCooP/be.werkmetzin.wpcivi/files/170409/civicrmerror.log.zip

**Comment by cdhassell** [comment]
Ok fair enough.  For anyone else tripped up by this issue, here is the solution.  
It is not a permissions problem.  The issue is that the resources file path is hard coded in CRM/Wpcivi/Config.php, line 21.  The install from the tarball creates a directory called be.werkmetzin.wpcivi-master, however the code expects be.werkmetzin.wpcivi.  You have to make the paths match in order for the install to proceed.

**Comment by ErikHommel** [comment]
hi @cdhassell thanks for your comments!
I would add that it is not an issue, the extension never meant to be a generic solution. It is meant as a framework, and yes you will have to modify the code to make it work in your specific situation. That is the reason why the resources path is hard-coded, it is only meant to work in that specific situation?
